create table
  public.articles (
    id bigint generated by default as identity not null,
    seo jsonb not null,
    title text null,
    slug text not null,
    image text not null,
    user uuid null,
    public boolean not null default false,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    content jsonb null,
    constraint articles_pkey primary key (id),
    constraint articles_slug_key unique (slug),
    constraint articles_user_fkey foreign key ("user") references users (uuid) on delete cascade
  ) tablespace pg_default;

create trigger handle_updated_at before
update on articles for each row
execute function moddatetime ('updated_at');