create table
  public.article (
    id bigint generated by default as identity not null,
    seo json not null,
    title text not null,
    slug text not null,
    content json null,
    image text not null,
    user uuid not null,
    public boolean not null default false,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    constraint article_pkey primary key (id),
    constraint article_user_fkey foreign key ("user") references "user" (uuid)
  ) tablespace pg_default;

create trigger handle_updated_at before update on articles
  for each row execute procedure moddatetime (updated_at);

-- create_user_on_signup
--   begin 
--   INSERT INTO public.user(id)
--   VALUES(
--     NEW.id
--   );
  
--   RETURN NEW;
-- end;